Update slice.yml

diff --git a/.github/workflows/slice.yml b/.github/workflows/slice.yml
--- a/.github/workflows/slice.yml
+++ b/.github/workflows/slice.yml
@@ -87,10 +87,10 @@ jobs:
         FILE_NAME=$(basename "$SRC_FILE")
         HTTP_STATUS=$(curl -o "$FILE_NAME" -w "%{http_code}" -s "$SRC_FILE")
         echo "$HTTP_STATUS"
-        if [ "$HTTP_STATUS" -ne "0" ]; then
-          ./sync-slice-status.sh ${{ inputs['jobId'] }} ${{ secrets.SLICE_CALLBACK }} "Download Model Failed."
-          exit 1
-        fi
+        # if [ "$HTTP_STATUS" -ne "0" ]; then
+        #   ./sync-slice-status.sh ${{ inputs['jobId'] }} ${{ secrets.SLICE_CALLBACK }} "Download Model Failed."
+        #   exit 1
+        # fi
         
         ABSOLUTE_PATH=$(realpath "$FILE_NAME")
         echo "FILE_ABSOLUTE_PATH=$ABSOLUTE_PATH" >> $GITHUB_ENV
